/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-bright": "#fdf7ff",
        "surface-container-low": "#f8f2fa",
        "on-secondary-fixed-variant": "#4b4263",
        "on-primary-container": "#e0d2ff",
        "primary-fixed": "#e9ddff",
        "secondary": "#63597c",
        "surface-container-highest": "#e6e0e9",
        "outline": "#7a7582",
        "tertiary-fixed-dim": "#e7c365",
        "on-secondary": "#ffffff",
        "surface-container-high": "#ece6ee",
        "on-tertiary": "#ffffff",
        "on-secondary-container": "#645a7d",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#4f378a",
        "surface": "#fdf7ff",
        "background": "#fdf7ff",
        "surface-tint": "#6750a4",
        "secondary-container": "#e1d4fd",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed": "#e9ddff",
        "primary-container": "#6750a4",
        "on-secondary-fixed": "#1f1635",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#22005d",
        "on-background": "#1d1b20",
        "on-tertiary-fixed": "#241a00",
        "tertiary-container": "#c9a74d",
        "surface-container": "#f2ecf4",
        "outline-variant": "#cbc4d2",
        "on-error-container": "#93000a",
        "tertiary": "#765b00",
        "on-tertiary-fixed-variant": "#594400",
        "primary": "#4f378a",
        "on-tertiary-container": "#503d00",
        "inverse-surface": "#322f35",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#cdc0e9",
        "inverse-on-surface": "#f5eff7",
        "surface-dim": "#ded8e0",
        "surface-variant": "#e6e0e9",
        "inverse-primary": "#cfbcff",
        "primary-fixed-dim": "#cfbcff",
        "on-surface-variant": "#494551",
        "tertiary-fixed": "#ffdf93",
        "on-surface": "#1d1b20",
        "error": "#ba1a1a",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "stack-md": "16px",
        "stack-lg": "32px",
        "margin-mobile": "16px",
        "stack-sm": "8px",
        "unit": "8px",
        "container-max": "1280px",
        "margin-desktop": "40px",
        "gutter": "24px",
      },
      fontFamily: {
        "body-lg": ["Inter"],
        "label-md": ["Inter"],
        "headline-sm": ["Inter"],
        "headline-lg": ["Inter"],
        "body-md": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "label-sm": ["Inter"],
        "body-sm": ["Inter"],
        "headline-md": ["Inter"],
        "display-lg": ["Inter"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
}
